apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: golang-order-service
  name: golang-order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-order-service
  template:
    metadata:
      labels:
        app: golang-order-service
    spec:
      containers:
      - image: pamitedu/golang-order-service:latest
        name: golang-order-service
        # env:
        #   - name: AUTH_SERVICE_URL
        #     value: http://ruby-authentication-service:4567
        envFrom:
          - configMapRef:
              name: golang-order-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-order-service
  name: golang-order-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: golang-order-service
  type: NodePort
